#!/bin/sh

# Remember where we started; this is where our source checkout lives.
src=`pwd`
# Load the module command and use it to load MPI.
. /etc/profile.d/modules.sh
module load mpi
# Create a directory to hold the build and build IBAMR
mkdir /bld
cd /bld
cmake \
  -DCMAKE_C_FLAGS="-O3 -fPIC -march=native" \
  -DCMAKE_CXX_FLAGS="-O3 -fPIC -march=native" \
  -DCMAKE_Fortran_FLAGS="-O3 -fPIC -march=native" \
  -DCMAKE_INSTALL_PREFIX=/ibamr \
  -DSAMRAI_ROOT=/samrai \
  -DLIBMESH_ROOT=/libmesh \
  -DLIBMESH_METHOD=OPT \
  -DPETSC_ROOT=/petsc/x86_64 \
  -DHYPRE_ROOT=/petsc/x86_64 \
  -DNUMDIFF_ROOT=/numdiff \
  ${src}
time make -j2
time make -j2 install
