#!/bin/bash
set -e
# Run script that removes dimension template first.
perl ./removeTemplateOnDim.pl "$1"
perl ./loadBalancer.pl "$1"
perl ./removePointer.pl "$1"
perl ./use_static_pointer_cast.pl "$1"
for filename in *.pl; do
    echo $filename
    if [ "$filename" = "removeTemplateOnDim.pl" ] || [ "$filename" = "loadBalancer.pl" ] || [ "$filename" = "convertIncludePaths.pl" ] || [ "$filename" = "removePointer.pl" ] || [ "$filename" = "use_static_pointer_cast.pl" ]; then
        continue
    else
        perl "$filename" "$1"
    fi
done
perl ./convertIncludePaths.pl "$2" "$1"

