#ifndef included_IBLagrangianForceStrategy
#define included_IBLagrangianForceStrategy

// Filename: IBLagrangianForceStrategy.h
// Created on 03 May 2005 by Boyce Griffith (boyce@mstu1.cims.nyu.edu)
// Last modified: <03.Oct.2006 10:31:56 boyce@boyce-griffiths-powerbook-g4-15.local>

/////////////////////////////// INCLUDES /////////////////////////////////////

// IBAMR INCLUDES
#include <ibamr/LDataManager.h>
#include <ibamr/LNodeLevelData.h>

// SAMRAI INCLUDES
#include <PatchHierarchy.h>
#include <tbox/DescribedClass.h>
#include <tbox/Pointer.h>

/////////////////////////////// CLASS DEFINITION /////////////////////////////

namespace IBAMR
{
/*!
 * @brief Class IBLagrangianForceStrategy provides a mechanism for
 * specifying forces on the curvilinear mesh.
 */
class IBLagrangianForceStrategy
    : public virtual SAMRAI::tbox::DescribedClass
{
public:
    /*!
     * @brief Default constructor.
     */
    IBLagrangianForceStrategy();

    /*!
     * @brief Destructor.
     */
    virtual ~IBLagrangianForceStrategy();

    /*!
     * @brief Compute the curvilinear force (density) generated by the
     * given configuration of the curvilinear mesh.
     */
    virtual void computeLagrangianForce(
        SAMRAI::tbox::Pointer<LNodeLevelData> F_data,
        SAMRAI::tbox::Pointer<LNodeLevelData> X_data,
        const SAMRAI::tbox::Pointer<SAMRAI::hier::PatchHierarchy<NDIM> > hierarchy,
        const int level_number,
        const double data_time,
        const LDataManager* const lag_manager) = 0;

    /*!
     * @brief Setup the data needed to compute the curvilinear force
     * (density) on the specified level of the patch hierarchy.
     *
     * NOTE: A default empty implementation is provided.
     */
    virtual void initializeLevelData(
        const SAMRAI::tbox::Pointer<SAMRAI::hier::PatchHierarchy<NDIM> > hierarchy,
        const int level_number,
        const double init_data_time,
        const bool initial_time,
        const LDataManager* const lag_manager);

private:
    /*!
     * @brief Copy constructor.
     *
     * NOTE: This constructor is not implemented and should not be
     * used.
     *
     * @param from The value to copy to this object.
     */
    IBLagrangianForceStrategy(
        const IBLagrangianForceStrategy& from);

    /*!
     * @brief Assignment operator.
     *
     * NOTE: This operator is not implemented and should not be used.
     *
     * @param that The value to assign to this object.
     *
     * @return A reference to this object.
     */
    IBLagrangianForceStrategy& operator=(
        const IBLagrangianForceStrategy& that);
};
}// namespace IBAMR

/////////////////////////////// INLINE ///////////////////////////////////////

//#include "IBLagrangianForceStrategy.I"

//////////////////////////////////////////////////////////////////////////////

#endif //#ifndef included_IBLagrangianForceStrategy
