clear all; close all; clc;

length = [3 5 9 13 17 21];
num_rows = [20 40 80 120 160 200];
num_depth = 1;

num_rows11 = (length - 1).*8;
Dof = length .* num_rows11;

% 90 71 65 17
% B = load('data/D_500_0.0025');
% 
%     for k = 1:length
%         for j = 1:num_rows
%             idx = (j-1)*length + k;
%             X(j,k) = B(idx, 1);
%             Y(j,k) = B(idx, 2);
%         end
%     end
% 
% yyy1 = 0.1 * ones(1,length);
% yyy2 = 0.9 * ones(1,length);
%     
% xpi = [X(length,:) X(length:num_rows-length+1,length)' X(num_rows-length+1,length:-1:1) X(num_rows-length+1:-1:length,1)'];
% ypi = [yyy1 Y(length:num_rows-length+1,length)' yyy2 Y(num_rows-length+1:-1:length,1)'];
% ini_area = polyarea(xpi,ypi);
% 
% figure(3)
% scatter(xpi,ypi)
color=[0       0.447   0.741;...
        0.85    0.325   0.098;...
        0.929   0.694   0.125;...
        0.494   0.184   0.556;...
        0.5	    0.8     0.35];

for l = 1:5
    dt = 1.0e-4 / num_rows(l);
    IterNum(l) = 0.3 / dt / 100;
for i = 1:IterNum(l)
    nstep(l,i) = i*100;
    ntime(l,i) = i*100*dt;
    B = load(['data_' num2str(num_rows(l)) '/D_' num2str(nstep(l,i))]);

    for k = 1:length(l)
        for j = 1:num_rows(l)
            idx = (j-1)*length(l) + k;
            Xt(j,k) = B(idx, 1) + B(idx,3);
            Yt(j,k) = B(idx, 2) + B(idx,4);
            U(j,k) = B(idx, 3);
            V(j,k) = B(idx, 4);
            D(j,k) = B(idx, 5);
        end
    end
    
%     xp = [ Xt(length,1) X(length,:) Xt(length,length) Xt(length:num_rows-length+1,length)' Xt(num_rows-length+1,length) X(num_rows-length+1,length:-1:1) Xt(num_rows-length+1,1) Xt(num_rows-length+1:-1:length,1)'];
%     yp = [Yt(length,1) yyy1 Yt(length,length) Yt(length:num_rows-length+1,length)' Yt(num_rows-length+1,length) yyy2 Yt(num_rows-length+1,1) Yt(num_rows-length+1:-1:length,1)'];
%     area(i) = (polyarea(xp,yp)-ini_area)/ini_area * 100;
%     
%     figure(2)
%     scatter(xp,yp);
    
    x_disp(l,i) = U(num_rows(l)/2+1,length(l));
    y_disp(l,i) = V(num_rows(l)/2+1,length(l));
    damage(l,i) = D(num_rows(l)/2+1,1);
end
end

figure(5)
ppp(1) = plot([0 ntime(1,1:IterNum(1))],[0 x_disp(1,1:IterNum(1))],'-','color',color(1,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(1,:)                         ...
            , 'MarkerEdgeColor' , color(1,:));
hold on
ppp(2) = plot([0 ntime(2,1:IterNum(2))],[0 x_disp(2,1:IterNum(2))],'--','color',color(2,:)                         ...
            , 'linewidth'       , 3.0                          ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(2,:)                         ...
            , 'MarkerEdgeColor' , color(2,:));
hold on
ppp(3) = plot([0 ntime(3,1:IterNum(3))],[0 x_disp(3,1:IterNum(3))],'-.','color',color(3,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(3,:)                         ...
            , 'MarkerEdgeColor' , color(3,:));
hold on
ppp(4) = plot([0 ntime(4,1:IterNum(4))],[0 x_disp(4,1:IterNum(4))],':','color',color(4,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(4,:)                         ...
            , 'MarkerEdgeColor' , color(4,:));
% hold on
% ppp(5) = plot([0 ntime(5,1:IterNum(5))],[0 x_disp(5,1:IterNum(5))],'-.','color',color(5,:)                         ...
%             , 'linewidth'       , 3.0                           ...
%             , 'MarkerSize'      , 10                             ...
%             , 'MarkerFaceColor' , color(5,:)                         ...
%             , 'MarkerEdgeColor' , color(5,:));

xlabel('Time ($s$)' , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
ylabel({'Horizontal Disp (cm)'} , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
set(gca, 'FontName'      , 'arial'                  ...
       , 'fontSize'      , 25                       ...
       , 'fontWeight'    , 'normal'                 ...
       , 'position'      , [0.165 0.19 0.8 0.7]);
   

ylim([-0.001 0.4])
xlim([0 0.3])

h = figure(5);
fig_props.figW = 18;
fig_props.figH = 16;
set(h, 'units'        , 'centimeters'     ...
     , 'color'        , [1 1 1]           ...
     , 'position'     , [1 1 fig_props.figW fig_props.figH] ...
     , 'PaperUnits'   , 'centimeters'     ...
     , 'PaperSize'    , [fig_props.figW fig_props.figH]     ...
     , 'PaperPosition', [0 0 fig_props.figW fig_props.figH])
print(h,'-dpdf','ELS_BND_notch_disp1');


figure(6)
pp(1) = plot([0 ntime(1,1:IterNum(1))],[0 y_disp(1,1:IterNum(1))],'-','color',color(1,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(1,:)                         ...
            , 'MarkerEdgeColor' , color(1,:));
hold on
pp(2) = plot([0 ntime(2,1:IterNum(2))],[0 y_disp(2,1:IterNum(2))],'--','color',color(2,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(2,:)                         ...
            , 'MarkerEdgeColor' , color(2,:));
hold on
pp(3) = plot([0 ntime(3,1:IterNum(3))],[0 y_disp(3,1:IterNum(3))],'-.','color',color(3,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(3,:)                         ...
            , 'MarkerEdgeColor' , color(3,:));
hold on
pp(4) = plot([0 ntime(4,1:IterNum(4))],[0 y_disp(4,1:IterNum(4))],':','color',color(4,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(4,:)                         ...
            , 'MarkerEdgeColor' , color(4,:));
% hold on
% pp(5) = plot([0 ntime(5,1:IterNum(5))],[0 y_disp(5,1:IterNum(5))],'-.','color',color(5,:)                         ...
%             , 'linewidth'       , 3.0                           ...
%             , 'MarkerSize'      , 10                             ...
%             , 'MarkerFaceColor' , color(5,:)                         ...
%             , 'MarkerEdgeColor' , color(5,:));
        
xlabel('Time ($s$)' , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
ylabel({'Vertical Disp (cm)'} , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
set(gca, 'FontName'      , 'arial'                  ...
       , 'fontSize'      , 25                       ...
       , 'fontWeight'    , 'normal'                 ...
       , 'position'      , [0.165 0.19 0.8 0.7]);

hleg = legend(pp  ,{'$\Delta X = 1/20$','$\Delta X = 1/40$','$\Delta X = 1/80$','$\Delta X = 1/120$'}                ...
       , 'Interpreter', 'latex'                   ...
       , 'FontName'   , 'arial'                   ...
       , 'fontSize'   , 20                        ...
       , 'Location'   , 'northwest');
legend boxoff
set(hleg, 'FontName'  , 'arial'                   ...
        , 'fontSize'  , 23);   
   
ylim([-0.005 0.4])
yticks([0 0.1 0.2 0.3 0.4])
xlim([0 0.3])
   
h = figure(6);
fig_props.figW = 18;
fig_props.figH = 16;
set(h, 'units'        , 'centimeters'     ...
     , 'color'        , [1 1 1]           ...
     , 'position'     , [1 1 fig_props.figW fig_props.figH] ...
     , 'PaperUnits'   , 'centimeters'     ...
     , 'PaperSize'    , [fig_props.figW fig_props.figH]     ...
     , 'PaperPosition', [0 0 fig_props.figW fig_props.figH])
print(h,'-dpdf','ELS_BND_notch_disp2');
   
figure(7)
p(1) = plot([0 ntime(1,1:IterNum(1))],[damage(1,1) damage(1,1:IterNum(1))],'-','color',color(1,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(1,:)                         ...
            , 'MarkerEdgeColor' , color(1,:));
hold on
p(2) = plot([0 ntime(2,1:IterNum(2))],[damage(2,1) damage(2,1:IterNum(2))],'--','color',color(2,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(2,:)                         ...
            , 'MarkerEdgeColor' , color(2,:));
hold on
p(3) = plot([0 ntime(3,1:IterNum(3))],[damage(3,1) damage(3,1:IterNum(3))],'-.','color',color(3,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(3,:)                         ...
            , 'MarkerEdgeColor' , color(3,:));
hold on
p(4) = plot([0 ntime(4,1:IterNum(4))],[damage(4,1) damage(4,1:IterNum(4))],':','color',color(4,:)                         ...
            , 'linewidth'       , 3.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(4,:)                         ...
            , 'MarkerEdgeColor' , color(4,:));
% hold on
% p(5) = plot([0 ntime(5,1:IterNum(5))],[damage(5,1) damage(5,1:IterNum(5))],'-.','color',color(5,:)                         ...
%             , 'linewidth'       , 3.0                           ...
%             , 'MarkerSize'      , 10                             ...
%             , 'MarkerFaceColor' , color(5,:)                         ...
%             , 'MarkerEdgeColor' , color(5,:));
        
xlabel('Time ($s$)' , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
ylabel({'Damage $\varphi$'} , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
set(gca, 'FontName'      , 'arial'                  ...
       , 'fontSize'      , 25                       ...
       , 'fontWeight'    , 'normal'                 ...
       , 'position'      , [0.165 0.19 0.8 0.7]);
   
hleg = legend(p  ,{'$\Delta X = 1/20$','$\Delta X = 1/40$','$\Delta X = 1/80$','$\Delta X = 1/120$'}                ...
       , 'Interpreter', 'latex'                   ...
       , 'FontName'   , 'arial'                   ...
       , 'fontSize'   , 20                        ...
       , 'Location'   , 'northwest');
legend boxoff
set(hleg, 'FontName'  , 'arial'                   ...
        , 'fontSize'  , 23);

ylim([0 0.5])
xlim([0 0.3])

h = figure(7);
fig_props.figW = 18;
fig_props.figH = 16;
set(h, 'units'        , 'centimeters'     ...
     , 'color'        , [1 1 1]           ...
     , 'position'     , [1 1 fig_props.figW fig_props.figH] ...
     , 'PaperUnits'   , 'centimeters'     ...
     , 'PaperSize'    , [fig_props.figW fig_props.figH]     ...
     , 'PaperPosition', [0 0 fig_props.figW fig_props.figH])
print(h,'-dpdf','ELS_BND_notch_damage');

rupture_time = [ntime(1,417) ntime(2,754) ntime(3,1344) ntime(4,1992) ntime(5,2694)];

figure(8)
plot(Dof(1:5),rupture_time(1:5),'-o','color',color(1,:)                         ...
            , 'linewidth'       , 10.0                           ...
            , 'MarkerSize'      , 10                             ...
            , 'MarkerFaceColor' , color(1,:)                         ...
            , 'MarkerEdgeColor' , color(1,:));
xlabel('Degrees of Freedom' , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
ylabel({'Time (s)'} , 'Interpreter', 'latex'   ...
      , 'FontName'       , 'arial'                  ...
      , 'fontSize'       , 25                       ...
      , 'fontWeight'     , 'bold')
set(gca, 'FontName'      , 'arial'                  ...
       , 'fontSize'      , 25                       ...
       , 'fontWeight'    , 'normal'                 ...
       , 'position'      , [0.165 0.19 0.8 0.7]);
ylim([0.15 0.25])
% xlim([1 1350])

h = figure(8);
fig_props.figW = 19;
fig_props.figH = 16;
set(h, 'units'        , 'centimeters'     ...
     , 'color'        , [1 1 1]           ...
     , 'position'     , [1 1 fig_props.figW fig_props.figH] ...
     , 'PaperUnits'   , 'centimeters'     ...
     , 'PaperSize'    , [fig_props.figW fig_props.figH]     ...
     , 'PaperPosition', [0 0 fig_props.figW fig_props.figH])
print(h,'-dpdf','ELS_BND_notch_time');