// Config files
#include <IBAMR_config.h>
#include <SAMRAI_config.h>

// Headers for basic PETSc functions
#include <petsc.h>

// Headers for basic SAMRAI objects
#include <PatchLevel.h>
#include <VariableDatabase.h>
#include <tbox/Database.h>
#include <tbox/InputDatabase.h>
#include <tbox/InputManager.h>
#include <tbox/MPI.h>
#include <tbox/PIO.h>
#include <tbox/Pointer.h>
#include <tbox/RestartManager.h>
#include <tbox/SAMRAIManager.h>
#include <tbox/Utilities.h>

// Headers for major algorithm/data structure objects
#include <BergerRigoutsos.h>
#include <CartesianGridGeometry.h>
#include <GriddingAlgorithm.h>
#include <LoadBalancer.h>
#include <PatchHierarchy.h>
#include <StandardTagAndInitialize.h>
#include <VisItDataWriter.h>

// Headers for application-specific algorithm/data structure objects
#include <ibamr/GodunovAdvector.h>
#include <ibamr/IBHierarchyIntegrator.h>
#include <ibamr/IBStandardForceGen.h>
#include <ibamr/IBStandardInitializer.h>
#include <ibamr/INSHierarchyIntegrator.h>
#include <ibamr/LagSiloDataWriter.h>

#include <stools/TimeDependentLocationIndexRobinBcCoefs.h>

using namespace IBAMR;
using namespace SAMRAI;
using namespace STOOLS;
using namespace std;

/*!
 * \brief Function to compute the force generated by a linear spring
 * with a non-zero resting length.
 */
inline void
linear_spring_force(
    double F[NDIM],
    const double D[NDIM],
    const double& stf,
    const double& rst,
    const int& lag_mastr_idx,
    const int& lag_slave_idx)
{
    (void) lag_mastr_idx;
    (void) lag_slave_idx;

    /*
     * Compute the distance between the "master" and "slave" nodes.
     */
    double r_sq = 0.0;
    for (int d = 0; d < NDIM; ++d)
    {
        r_sq += D[d]*D[d];
    }
    const double r = sqrt(r_sq);

    /*
     * Compute the force applied to the "master" node.
     */
    if (rst > numeric_limits<double>::epsilon() &&
        r   > numeric_limits<double>::epsilon())
    {
        const double ratio = r/rst - 1.0;
        const double T = stf*ratio;
        for (int d = 0; d < NDIM; ++d)
        {
            F[d] = T*D[d]/r;
        }
    }
    return;
}// linear_spring_force

/************************************************************************
 * For each run, the input filename and restart information (if         *
 * needed) must be given on the command line.  For non-restarted case,  *
 * command line is:                                                     *
 *                                                                      *
 *    executable <input file name>                                      *
 *                                                                      *
 * For restarted run, command line is:                                  *
 *                                                                      *
 *    executable <input file name> <restart directory> <restart number> *
 *                                                                      *
 ************************************************************************
 */

int main(int argc, char* argv[])
{
    /*
     * Initialize PETSc, MPI, and SAMRAI.
     */
    PetscInitialize(&argc,&argv,PETSC_NULL,PETSC_NULL);
    tbox::MPI::setCommunicator(PETSC_COMM_WORLD);
    tbox::SAMRAIManager::startup();

    {// cleanup all smart Pointers prior to shutdown

        /*
         * Process command line and enable logging.
         */
        string input_filename;
        string restart_read_dirname;
        int restore_num = 0;

        bool is_from_restart = false;

        if (argc == 1)
        {
            tbox::pout << "USAGE:  " << argv[0] << " <input filename> "
                       << "<restart dir> <restore number> [options]\n"
                       << "  options:\n"
                       << "  PETSc command line options; use -help for more information"
                       << endl;
            tbox::MPI::abort();
            return -1;
        }
        else
        {
            input_filename = argv[1];
            if (argc >= 4)
            {
                FILE* fstream = NULL;
                if (tbox::MPI::getRank() == 0)
                {
                    fstream = fopen(argv[2], "r");
                }
                int worked = (fstream ? 1 : 0);
#ifdef HAVE_MPI
                worked = tbox::MPI::bcast(worked, 0);
#endif
                if (worked)
                {
                    restart_read_dirname = argv[2];
                    restore_num = atoi(argv[3]);
                    is_from_restart = true;
                }
                if (fstream) fclose(fstream);
            }
        }

        tbox::plog << "input_filename = " << input_filename << endl;
        tbox::plog << "restart_read_dirname = " << restart_read_dirname << endl;
        tbox::plog << "restore_num = " << restore_num << endl;

        /*
         * Create input database and parse all data in input file.
         */
        tbox::Pointer<tbox::Database> input_db = new tbox::InputDatabase("input_db");
        tbox::InputManager::getManager()->parseInputFile(input_filename, input_db);

        /*
         * Retrieve "Main" section of the input database.  First, read
         * dump information, which is used for writing plot files.
         * Second, if proper restart information was given on command
         * line, and the restart interval is non-zero, create a restart
         * database.
         */
        tbox::Pointer<tbox::Database> main_db = input_db->getDatabase("Main");

        string log_file_name = "IB.log";
        if (main_db->keyExists("log_file_name"))
        {
            log_file_name = main_db->getString("log_file_name");
        }
        bool log_all_nodes = false;
        if (main_db->keyExists("log_all_nodes"))
        {
            log_all_nodes = main_db->getBool("log_all_nodes");
        }
        if (log_all_nodes)
        {
            tbox::PIO::logAllNodes(log_file_name);
        }
        else
        {
            tbox::PIO::logOnlyNodeZero(log_file_name);
        }

        int viz_dump_interval = 0;
        if (main_db->keyExists("viz_dump_interval"))
        {
            viz_dump_interval = main_db->getInteger("viz_dump_interval");
        }

        tbox::Array<string> viz_writer(1);
        viz_writer[0] = "VisIt";
        string viz_dump_filename;
        string visit_dump_dirname;
        bool uses_visit = false;
        int visit_number_procs_per_file = 1;
        if (viz_dump_interval > 0)
        {
            if (main_db->keyExists("viz_writer"))
            {
                viz_writer = main_db->getStringArray("viz_writer");
            }
            if (main_db->keyExists("viz_dump_filename"))
            {
                viz_dump_filename = main_db->getString("viz_dump_filename");
            }
            string viz_dump_dirname;
            if (main_db->keyExists("viz_dump_dirname"))
            {
                viz_dump_dirname = main_db->getString("viz_dump_dirname");
            }
            for (int i = 0; i < viz_writer.getSize(); i++)
            {
                if (viz_writer[i] == "VisIt") uses_visit = true;
            }
            if (uses_visit)
            {
                visit_dump_dirname = viz_dump_dirname;
            }
            else
            {
                TBOX_ERROR("main(): "
                           << "\nUnrecognized 'viz_writer' entry..."
                           << "\nOptions are 'Vizamrai' and/or 'VisIt'"
                           << endl);
            }
            if (uses_visit)
            {
                if (viz_dump_dirname.empty())
                {
                    TBOX_ERROR("main(): "
                               << "\nviz_dump_dirname is null ... "
                               << "\nThis must be specified for use with VisIt"
                               << endl);
                }
                if (main_db->keyExists("visit_number_procs_per_file"))
                {
                    visit_number_procs_per_file = main_db->getInteger("visit_number_procs_per_file");
                }
            }
        }

        const bool viz_dump_data = (viz_dump_interval > 0);

        int restart_interval = 0;
        if (main_db->keyExists("restart_interval"))
        {
            restart_interval = main_db->getInteger("restart_interval");
        }

        string restart_write_dirname;
        if (restart_interval > 0)
        {
            if (main_db->keyExists("restart_write_dirname"))
            {
                restart_write_dirname = main_db->getString("restart_write_dirname");
            }
            else
            {
                TBOX_ERROR("restart_interval > 0, but key `restart_write_dirname'"
                           << " not specifed in input file");
            }
        }

        const bool write_restart = restart_interval > 0
            && !restart_write_dirname.empty();

        /*
         * Get the restart manager and root restart database.  If run is
         * from restart, open the restart file.
         */
        tbox::RestartManager* restart_manager = tbox::RestartManager::getManager();
        if (is_from_restart)
        {
            restart_manager->openRestartFile(
                restart_read_dirname, restore_num, tbox::MPI::getNodes());
        }

        /*
         * Create boundary condition specification objects.
         */
        solv::LocationIndexRobinBcCoefs<NDIM> u0_bc_coef(
            "u0_bc_coef", tbox::Pointer<tbox::Database>(NULL));
        u0_bc_coef.setBoundaryValue(0, 0.0);  // x lower boundary
        u0_bc_coef.setBoundaryValue(1, 0.0);  // x upper boundary
        u0_bc_coef.setBoundarySlope(2, 0.0);  // y lower boundary
        u0_bc_coef.setBoundaryValue(3, 0.0);  // y upper boundary

        TimeDependentLocationIndexRobinBcCoefs u1_bc_coef(
            "u1_bc_coef", tbox::Pointer<tbox::Database>(NULL));
        for (int i = 0; i < 2*NDIM; ++i)
        {
            u1_bc_coef.setBoundaryTimeConstant(i,2.5e-3);
        }

        u1_bc_coef.setBoundaryInitialSlope(0, 0.0);  // x lower boundary
        u1_bc_coef.setBoundaryInitialSlope(1, 0.0);  // x upper boundary
        u1_bc_coef.setBoundaryInitialSlope(2, 0.0);  // y lower boundary
        u1_bc_coef.setBoundaryInitialValue(3, 0.0);  // y upper boundary

        u1_bc_coef.setBoundaryFinalSlope(0,   0.0);  // x lower boundary
        u1_bc_coef.setBoundaryFinalSlope(1,   0.0);  // x upper boundary
        u1_bc_coef.setBoundaryFinalSlope(2,   0.0);  // y lower boundary
        u1_bc_coef.setBoundaryFinalValue(3,-280.0);  // y upper boundary

        vector<const solv::RobinBcCoefStrategy<NDIM>*> U_bc_coefs(NDIM);
        U_bc_coefs[0] = &u0_bc_coef;
        U_bc_coefs[1] = &u1_bc_coef;

        solv::LocationIndexRobinBcCoefs<NDIM> phi_bc_coef(
            "phi_bc_coef", tbox::Pointer<tbox::Database>(NULL));
        phi_bc_coef.setBoundarySlope(0, 0.0);  // x lower boundary
        phi_bc_coef.setBoundarySlope(1, 0.0);  // x upper boundary
        phi_bc_coef.setBoundaryValue(2, 0.0);  // y lower boundary
        phi_bc_coef.setBoundarySlope(3, 0.0);  // y upper boundary

        /*
         * Create major algorithm and data objects which comprise application.
         * Each object will be initialized either from input data or restart
         * files, or a combination of both.  Refer to each class constructor
         * for details.  For more information on the composition of objects
         * for this application, see comments at top of file.
         */
        tbox::Pointer<geom::CartesianGridGeometry<NDIM> > grid_geometry =
            new geom::CartesianGridGeometry<NDIM>(
                "CartesianGeometry",
                input_db->getDatabase("CartesianGeometry"));

        tbox::Pointer<hier::PatchHierarchy<NDIM> > patch_hierarchy =
            new hier::PatchHierarchy<NDIM>(
                "PatchHierarchy",
                grid_geometry);

        tbox::Pointer<GodunovAdvector> predictor =
            new GodunovAdvector(
                "GodunovAdvector",
                input_db->getDatabase("GodunovAdvector"));

        tbox::Pointer<AdvDiffHierarchyIntegrator> adv_diff_integrator =
            new AdvDiffHierarchyIntegrator(
                "AdvDiffHierarchyIntegrator",
                input_db->getDatabase("AdvDiffHierarchyIntegrator"),
                patch_hierarchy, predictor);

        tbox::Pointer<HierarchyProjector> hier_projector =
            new HierarchyProjector(
                "HierarchyProjector",
                input_db->getDatabase("HierarchyProjector"),
                patch_hierarchy);
        hier_projector->setPhysicalBcCoef(&phi_bc_coef);

        tbox::Pointer<INSHierarchyIntegrator> navier_stokes_integrator =
            new INSHierarchyIntegrator(
                "INSHierarchyIntegrator",
                input_db->getDatabase("INSHierarchyIntegrator"),
                patch_hierarchy, predictor, adv_diff_integrator, hier_projector);
        navier_stokes_integrator->registerVelocityPhysicalBcCoefs(U_bc_coefs);

        tbox::Pointer<IBSpringForceGen> spring_force_generator =
            new IBSpringForceGen();
        spring_force_generator->registerSpringForceFunction(0,&linear_spring_force);
        tbox::Pointer<IBBeamForceGen> beam_force_generator =
            new IBBeamForceGen();
        tbox::Pointer<IBTargetPointForceGen> target_point_force_generator =
            new IBTargetPointForceGen();

        tbox::Pointer<IBStandardForceGen> force_generator =
            new IBStandardForceGen(
                spring_force_generator, beam_force_generator, target_point_force_generator);

        tbox::Pointer<IBHierarchyIntegrator> time_integrator =
            new IBHierarchyIntegrator(
                "IBHierarchyIntegrator",
                input_db->getDatabase("IBHierarchyIntegrator"),
                patch_hierarchy, navier_stokes_integrator, force_generator);

        tbox::Pointer<LNodeInitStrategy> initializer =
            new IBStandardInitializer(
                "IBStandardInitializer",
                input_db->getDatabase("IBStandardInitializer"));
        time_integrator->registerLNodeInitStrategy(initializer);

        tbox::Pointer<mesh::StandardTagAndInitialize<NDIM> > error_detector =
            new mesh::StandardTagAndInitialize<NDIM>(
                "StandardTagAndInitialize",
                time_integrator,
                input_db->getDatabase("StandardTagAndInitialize"));

        tbox::Pointer<mesh::BergerRigoutsos<NDIM> > box_generator =
            new mesh::BergerRigoutsos<NDIM>();

        tbox::Pointer<mesh::LoadBalancer<NDIM> > load_balancer =
            new mesh::LoadBalancer<NDIM>(
                "LoadBalancer",
                input_db->getDatabase("LoadBalancer"));

        tbox::Pointer<mesh::GriddingAlgorithm<NDIM> > gridding_algorithm =
            new mesh::GriddingAlgorithm<NDIM>(
                "GriddingAlgorithm",
                input_db->getDatabase("GriddingAlgorithm"),
                error_detector, box_generator, load_balancer);

        /*
         * Set up visualization plot file writer.
         */
        tbox::Pointer<appu::VisItDataWriter<NDIM> > visit_data_writer =
            new appu::VisItDataWriter<NDIM>(
                "VisIt Writer",
                visit_dump_dirname, visit_number_procs_per_file);
        tbox::Pointer<LagSiloDataWriter> silo_data_writer =
            new LagSiloDataWriter(
                "LagSiloDataWriter",
                visit_dump_dirname);

        if (uses_visit)
        {
            time_integrator->registerVisItDataWriter(visit_data_writer);
            time_integrator->registerLagSiloDataWriter(silo_data_writer);
        }

        /*
         * Initialize hierarchy configuration and data on all patches.
         * Then, close restart file and write initial state for
         * visualization.
         */
        time_integrator->initializeHierarchyIntegrator(gridding_algorithm);
        double dt_now = time_integrator->initializeHierarchy();

        dynamic_cast<IBStandardInitializer*>(initializer.getPointer())->
            registerLagSiloDataWriter(silo_data_writer);

        time_integrator->rebalanceCoarsestLevel();

        tbox::RestartManager::getManager()->closeRestartFile();

        /*
         * After creating all objects and initializing their state, we
         * print the input database contents to the log file.
         */
        tbox::plog << "\nCheck input data before simulation:" << endl;
        tbox::plog << "Input database..." << endl;
        input_db->printClassData(tbox::plog);

        /*
         * Write initial visualization files.
         */
        if (viz_dump_data)
        {
            if (uses_visit)
            {
                visit_data_writer->writePlotData(
                    patch_hierarchy,
                    time_integrator->getIntegratorStep(),
                    time_integrator->getIntegratorTime());
                silo_data_writer->writePlotData(
                    time_integrator->getIntegratorStep(),
                    time_integrator->getIntegratorTime());
            }
        }

        /*
         * Open file to output the coordinates of the end of the
         * fillament.
         */
        ofstream X_stream;
        if (tbox::MPI::getRank() == 0)
        {
            X_stream.open("X.coords", tbox::RestartManager::getManager()->isFromRestart() ? ios::app : ios::out);
            X_stream.setf(ios_base::scientific);
            X_stream.setf(ios_base::showpoint);
            if (!tbox::RestartManager::getManager()->isFromRestart())
            {
                X_stream << "time            x-coord         y-coord\n";
            }
            X_stream.width(9);
            X_stream.precision(8);
        }

        /*
         * Time step loop.  Note that the step count and integration
         * time are maintained by the time integrator object.
         */
        double loop_time = time_integrator->getIntegratorTime();
        double loop_time_end = time_integrator->getEndTime();

        int iteration_num = time_integrator->getIntegratorStep();

        while (!tbox::Utilities::deq(loop_time,loop_time_end) &&
               time_integrator->stepsRemaining())
        {
            iteration_num = time_integrator->getIntegratorStep() + 1;

            tbox::pout <<                                                       endl;
            tbox::pout << "++++++++++++++++++++++++++++++++++++++++++++++++" << endl;
            tbox::pout << "At begining of timestep # " <<  iteration_num - 1 << endl;
            tbox::pout << "Simulation time is " << loop_time                 << endl;

            double dt_new = time_integrator->advanceHierarchy(dt_now);

            loop_time += dt_now;
            dt_now = dt_new;

            tbox::pout <<                                                       endl;
            tbox::pout << "At end      of timestep # " <<  iteration_num - 1 << endl;
            tbox::pout << "Simulation time is " << loop_time                 << endl;
            tbox::pout << "++++++++++++++++++++++++++++++++++++++++++++++++" << endl;
            tbox::pout <<                                                       endl;

            /*
             * Determine the coordinates of the free end of the
             * filament.
             */
            int finest_hier_level = patch_hierarchy->getFinestLevelNumber();
            LDataManager* lag_manager = time_integrator->getLDataManager();

            vector<int> X_idx(1,-1);
            X_idx[0] = lag_manager->getNumberOfNodes(finest_hier_level) - 1;
            lag_manager->mapLagrangianToPETSc(X_idx, finest_hier_level);

            tbox::Pointer<LNodeLevelData> X_data = lag_manager->getLNodeLevelData(
                "X", finest_hier_level);
            Vec X_vec = X_data->getGlobalVec();

            int ilower, iupper;
            int ierr = VecGetOwnershipRange(X_vec, &ilower, &iupper);  PETSC_SAMRAI_ERROR(ierr);
            ilower /= NDIM;
            iupper /= NDIM;

            vector<double> X(NDIM,0.0);
            if (ilower <= X_idx[0] && X_idx[0] < iupper)
            {
                vector<int> idxs(NDIM);
                for (int d = 0; d < NDIM; ++d)
                {
                    idxs[d] = NDIM*X_idx[0]+d;
                }
                ierr = VecGetValues(X_vec, NDIM, &idxs[0], &X[0]);  PETSC_SAMRAI_ERROR(ierr);
            }
            tbox::MPI::sumReduction(&X[0],NDIM);

            /*
             * Output the coordinates of the free end of the filament.
             */
            if (tbox::MPI::getRank() == 0)
            {
                X_stream << loop_time;
                for (int d = 0; d < NDIM; ++d)
                {
                    X_stream << "  " << X[d];
                }
                X_stream << endl;
            }

            /*
             * At specified intervals, write restart and visualization files.
             */
            if (write_restart && iteration_num%restart_interval == 0)
            {
                tbox::RestartManager::getManager()->writeRestartFile(
                    restart_write_dirname, iteration_num);
            }

            if (viz_dump_data && iteration_num%viz_dump_interval == 0)
            {
                if (uses_visit)
                {
                    visit_data_writer->writePlotData(
                        patch_hierarchy, iteration_num, loop_time);
                    silo_data_writer->writePlotData(
                        iteration_num, loop_time);
                }
            }
        }

        /*
         * Ensure the last state is written out.
         */
        if (viz_dump_data && iteration_num%viz_dump_interval != 0)
        {
            if (uses_visit)
            {
                visit_data_writer->writePlotData(
                    patch_hierarchy, iteration_num, loop_time);
                silo_data_writer->writePlotData(
                    iteration_num, loop_time);
            }
        }

        /*
         * Close the file used to store the coordinates of the end of
         * the filament.
         */
        if (tbox::MPI::getRank() == 0)
        {
            X_stream.close();
        }

    }// cleanup all smart Pointers prior to shutdown

    tbox::SAMRAIManager::shutdown();
    PetscFinalize();

    return 0;
}// main
