// ---------------------------------------------------------------------
//
// Copyright (c) 2026 by the IBAMR developers
// All rights reserved.
//
// This file is part of IBAMR.
//
// IBAMR is free software and is distributed under the 3-clause BSD
// license. The full text of the license can be found in the file
// COPYRIGHT at the top level directory of IBAMR.
//
// ---------------------------------------------------------------------

#ifndef included_IBTK_samrai_compatibility_shim_aliases
#define included_IBTK_samrai_compatibility_shim_aliases

#include <samrai_compatibility/algs/SAMRAIHyperbolicLevelIntegrator.h>
#include <samrai_compatibility/algs/SAMRAIHyperbolicPatchStrategy.h>
#include <samrai_compatibility/algs/SAMRAITimeRefinementIntegrator.h>
#include <samrai_compatibility/algs/SAMRAITimeRefinementLevelStrategy.h>
#include <samrai_compatibility/appu/SAMRAIVisItDataWriter.h>
#include <samrai_compatibility/geom/SAMRAICartesianCellDoubleConservativeLinearRefine.h>
#include <samrai_compatibility/geom/SAMRAICartesianCellDoubleLinearRefine.h>
#include <samrai_compatibility/geom/SAMRAICartesianCellDoubleWeightedAverage.h>
#include <samrai_compatibility/geom/SAMRAICartesianGridGeometry.h>
#include <samrai_compatibility/geom/SAMRAICartesianPatchGeometry.h>
#include <samrai_compatibility/geom/SAMRAICartesianSideDoubleConservativeLinearRefine.h>
#include <samrai_compatibility/geom/SAMRAICartesianSideDoubleWeightedAverage.h>
#include <samrai_compatibility/hier/SAMRAIBasePatchHierarchy.h>
#include <samrai_compatibility/hier/SAMRAIBasePatchLevel.h>
#include <samrai_compatibility/hier/SAMRAIBoundaryBox.h>
#include <samrai_compatibility/hier/SAMRAIBox.h>
#include <samrai_compatibility/hier/SAMRAIBoxGeometry.h>
#include <samrai_compatibility/hier/SAMRAIBoxList.h>
#include <samrai_compatibility/hier/SAMRAIBoxOverlap.h>
#include <samrai_compatibility/hier/SAMRAIBoxTree.h>
#include <samrai_compatibility/hier/SAMRAICoarseFineBoundary.h>
#include <samrai_compatibility/hier/SAMRAIComponentSelector.h>
#include <samrai_compatibility/hier/SAMRAIGridGeometry.h>
#include <samrai_compatibility/hier/SAMRAIIndex.h>
#include <samrai_compatibility/hier/SAMRAIIntVector.h>
#include <samrai_compatibility/hier/SAMRAIPatch.h>
#include <samrai_compatibility/hier/SAMRAIPatchData.h>
#include <samrai_compatibility/hier/SAMRAIPatchDataFactory.h>
#include <samrai_compatibility/hier/SAMRAIPatchDescriptor.h>
#include <samrai_compatibility/hier/SAMRAIPatchGeometry.h>
#include <samrai_compatibility/hier/SAMRAIPatchHierarchy.h>
#include <samrai_compatibility/hier/SAMRAIPatchLevel.h>
#include <samrai_compatibility/hier/SAMRAIProcessorMapping.h>
#include <samrai_compatibility/hier/SAMRAIVariable.h>
#include <samrai_compatibility/hier/SAMRAIVariableContext.h>
#include <samrai_compatibility/hier/SAMRAIVariableDatabase.h>
#include <samrai_compatibility/math/SAMRAIArrayDataBasicOps.h>
#include <samrai_compatibility/math/SAMRAIHierarchyCellDataOpsInteger.h>
#include <samrai_compatibility/math/SAMRAIHierarchyCellDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIHierarchyDataOpsManager.h>
#include <samrai_compatibility/math/SAMRAIHierarchyDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIHierarchyEdgeDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIHierarchyFaceDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIHierarchyNodeDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIHierarchySideDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIPatchCellDataBasicOps.h>
#include <samrai_compatibility/math/SAMRAIPatchCellDataNormOpsReal.h>
#include <samrai_compatibility/math/SAMRAIPatchCellDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIPatchEdgeDataBasicOps.h>
#include <samrai_compatibility/math/SAMRAIPatchFaceDataBasicOps.h>
#include <samrai_compatibility/math/SAMRAIPatchFaceDataOpsReal.h>
#include <samrai_compatibility/math/SAMRAIPatchNodeDataBasicOps.h>
#include <samrai_compatibility/math/SAMRAIPatchSideDataBasicOps.h>
#include <samrai_compatibility/math/SAMRAIPatchSideDataNormOpsReal.h>
#include <samrai_compatibility/math/SAMRAIPatchSideDataOpsReal.h>
#include <samrai_compatibility/mesh/SAMRAIBergerRigoutsos.h>
#include <samrai_compatibility/mesh/SAMRAIBoxGeneratorStrategy.h>
#include <samrai_compatibility/mesh/SAMRAIGriddingAlgorithm.h>
#include <samrai_compatibility/mesh/SAMRAILoadBalanceStrategy.h>
#include <samrai_compatibility/mesh/SAMRAILoadBalancer.h>
#include <samrai_compatibility/mesh/SAMRAIStandardTagAndInitStrategy.h>
#include <samrai_compatibility/mesh/SAMRAIStandardTagAndInitialize.h>
#include <samrai_compatibility/mesh/SAMRAITagAndInitializeStrategy.h>
#include <samrai_compatibility/pdat/SAMRAIArrayData.h>
#include <samrai_compatibility/pdat/SAMRAICellData.h>
#include <samrai_compatibility/pdat/SAMRAICellDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAICellDoubleConstantRefine.h>
#include <samrai_compatibility/pdat/SAMRAICellGeometry.h>
#include <samrai_compatibility/pdat/SAMRAICellIndex.h>
#include <samrai_compatibility/pdat/SAMRAICellIterator.h>
#include <samrai_compatibility/pdat/SAMRAICellOverlap.h>
#include <samrai_compatibility/pdat/SAMRAICellVariable.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeData.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeGeometry.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeIndex.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeIterator.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeOverlap.h>
#include <samrai_compatibility/pdat/SAMRAIEdgeVariable.h>
#include <samrai_compatibility/pdat/SAMRAIFaceData.h>
#include <samrai_compatibility/pdat/SAMRAIFaceDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIFaceGeometry.h>
#include <samrai_compatibility/pdat/SAMRAIFaceIndex.h>
#include <samrai_compatibility/pdat/SAMRAIFaceIterator.h>
#include <samrai_compatibility/pdat/SAMRAIFaceOverlap.h>
#include <samrai_compatibility/pdat/SAMRAIFaceVariable.h>
#include <samrai_compatibility/pdat/SAMRAIIndexData.h>
#include <samrai_compatibility/pdat/SAMRAIIndexDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIIndexIterator.h>
#include <samrai_compatibility/pdat/SAMRAIIndexVariable.h>
#include <samrai_compatibility/pdat/SAMRAINodeData.h>
#include <samrai_compatibility/pdat/SAMRAINodeDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAINodeGeometry.h>
#include <samrai_compatibility/pdat/SAMRAINodeIndex.h>
#include <samrai_compatibility/pdat/SAMRAINodeIterator.h>
#include <samrai_compatibility/pdat/SAMRAINodeOverlap.h>
#include <samrai_compatibility/pdat/SAMRAINodeVariable.h>
#include <samrai_compatibility/pdat/SAMRAIOuteredgeData.h>
#include <samrai_compatibility/pdat/SAMRAIOuteredgeDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIOuteredgeVariable.h>
#include <samrai_compatibility/pdat/SAMRAIOuterfaceData.h>
#include <samrai_compatibility/pdat/SAMRAIOuterfaceDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIOuterfaceVariable.h>
#include <samrai_compatibility/pdat/SAMRAIOuternodeData.h>
#include <samrai_compatibility/pdat/SAMRAIOuternodeDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIOuternodeVariable.h>
#include <samrai_compatibility/pdat/SAMRAIOutersideData.h>
#include <samrai_compatibility/pdat/SAMRAIOutersideDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAIOutersideVariable.h>
#include <samrai_compatibility/pdat/SAMRAISideData.h>
#include <samrai_compatibility/pdat/SAMRAISideDataFactory.h>
#include <samrai_compatibility/pdat/SAMRAISideGeometry.h>
#include <samrai_compatibility/pdat/SAMRAISideIndex.h>
#include <samrai_compatibility/pdat/SAMRAISideIterator.h>
#include <samrai_compatibility/pdat/SAMRAISideOverlap.h>
#include <samrai_compatibility/pdat/SAMRAISideVariable.h>
#include <samrai_compatibility/solv/SAMRAICartesianRobinBcHelper.h>
#include <samrai_compatibility/solv/SAMRAIFACOperatorStrategy.h>
#include <samrai_compatibility/solv/SAMRAIFACPreconditioner.h>
#include <samrai_compatibility/solv/SAMRAILocationIndexRobinBcCoefs.h>
#include <samrai_compatibility/solv/SAMRAIPoissonSpecifications.h>
#include <samrai_compatibility/solv/SAMRAIRobinBcCoefStrategy.h>
#include <samrai_compatibility/solv/SAMRAISAMRAIVectorReal.h>
#include <samrai_compatibility/tbox/SAMRAIArray.h>
#include <samrai_compatibility/tbox/SAMRAIDatabase.h>
#include <samrai_compatibility/tbox/SAMRAIInputManager.h>
#include <samrai_compatibility/tbox/SAMRAIMathUtilities.h>
#include <samrai_compatibility/tbox/SAMRAIMemoryDatabase.h>
#include <samrai_compatibility/tbox/SAMRAINullDatabase.h>
#include <samrai_compatibility/tbox/SAMRAIPIO.h>
#include <samrai_compatibility/tbox/SAMRAIPointer.h>
#include <samrai_compatibility/tbox/SAMRAIReferenceCounter.h>
#include <samrai_compatibility/tbox/SAMRAIRestartManager.h>
#include <samrai_compatibility/tbox/SAMRAISAMRAIManager.h>
#include <samrai_compatibility/tbox/SAMRAISAMRAI_MPI.h>
#include <samrai_compatibility/tbox/SAMRAISchedule.h>
#include <samrai_compatibility/tbox/SAMRAISerializable.h>
#include <samrai_compatibility/tbox/SAMRAITimer.h>
#include <samrai_compatibility/tbox/SAMRAITimerManager.h>
#include <samrai_compatibility/tbox/SAMRAITransaction.h>
#include <samrai_compatibility/tbox/SAMRAIUtilities.h>
#include <samrai_compatibility/xfer/SAMRAICoarsenAlgorithm.h>
#include <samrai_compatibility/xfer/SAMRAICoarsenOperator.h>
#include <samrai_compatibility/xfer/SAMRAICoarsenPatchStrategy.h>
#include <samrai_compatibility/xfer/SAMRAICoarsenSchedule.h>
#include <samrai_compatibility/xfer/SAMRAIRefineAlgorithm.h>
#include <samrai_compatibility/xfer/SAMRAIRefineClasses.h>
#include <samrai_compatibility/xfer/SAMRAIRefineOperator.h>
#include <samrai_compatibility/xfer/SAMRAIRefinePatchStrategy.h>
#include <samrai_compatibility/xfer/SAMRAIRefineSchedule.h>
#include <samrai_compatibility/xfer/SAMRAIRefineTransactionFactory.h>
#include <samrai_compatibility/xfer/SAMRAIVariableFillPattern.h>

#endif // #ifndef included_IBTK_samrai_compatibility_shim_aliases
