function generate_single_level_case_01(vanka_repo, ref_dir)
% Generate MATLAB/Octave baseline references for single-level parity.
%
% Inputs:
%   vanka_repo: path to implicit_ib_coupling_aware_vanka repository
%   ref_dir:    output directory with eulerian_dof_map.ref present

if nargin < 2
    error('Usage: generate_single_level_case_01(vanka_repo, ref_dir)');
end

addpath(vanka_repo);

% Baseline parameters from test.m
Lx = 1.0; Ly = 1.0;
N = 32;
dx = Lx / N; dy = Ly / N;
mfac = 1;
r_cyl = 0.25;
alpha = 0.23;
beta = r_cyl^2 / alpha;
rho = 1.0; mu = 1.0e-2;
K = 1.0e2;
dt = 0.5 * dx;

ds = mfac * dx / r_cyl;
approx = round(2 * pi / ds);
ds = 2 * pi / approx;
theta = 0:ds:(2*pi - ds);
X1 = Lx .* (0.5 + alpha * cos(theta));
X2 = Ly .* (0.5 + beta * sin(theta));
X_nodes = [X1(:), X2(:)];
n_ib = size(X_nodes, 1);
n_u = N * N;
n_p = N * N;
n_tot = 3 * N * N;

% Interleaved lagrangian vector order [x1, y1, x2, y2, ...] to match IBAMR.
X_ref = zeros(2 * n_ib, 1);
for k = 1:n_ib
    X_ref(2 * k - 1) = X_nodes(k, 1);
    X_ref(2 * k) = X_nodes(k, 2);
end

% Read Eulerian DOF map generated by IBAMR.
[ib_to_mat_idx, map_n] = read_eulerian_dof_map(fullfile(ref_dir, 'eulerian_dof_map.ref'), N);
if map_n ~= n_tot
    error('DOF map size mismatch: map=%d expected=%d', map_n, n_tot);
end

% Build A in interleaved lag ordering.
A = build_lagrangian_A(X_nodes, K / (ds * ds), 0.0);
F_ref = A * X_ref;

% Build J in MATLAB Eulerian ordering and then reorder columns into IBAMR ordering.
J_mat = build_interp_matrix(X_nodes, N, dx, dy); % (2*n_ib) x (2*n_u)
J_full_mat = [J_mat, sparse(2 * n_ib, n_p)];
J_ref = J_full_mat(:, ib_to_mat_idx);
S_ref = J_ref';

% Build SAJ from MATLAB pieces in IBAMR ordering.
SAJ_ref = J_ref' * A * J_ref;

% Build Stokes matrix in MATLAB ordering with IB4 at all levels, reorder to
% IBAMR ordering, then extract A00.
L_stokes_mat = sparse(build_saddle_point_matrix_level_ib4_all(X_nodes, N, dx, ds, 0.0, dt, rho, mu, 1));
L_stokes_ref = L_stokes_mat(ib_to_mat_idx, ib_to_mat_idx);
A00_ref = L_stokes_ref(1:(2*n_u), 1:(2*n_u)) + SAJ_ref(1:(2*n_u), 1:(2*n_u));

% Emit references in IBAMR parity format.
write_vector_ref(fullfile(ref_dir, 'X.ref'), X_ref);
write_matrix_ref(fullfile(ref_dir, 'A.ref'), A);
write_vector_ref(fullfile(ref_dir, 'F.ref'), F_ref);
write_matrix_ref(fullfile(ref_dir, 'J.ref'), J_ref);
write_matrix_ref(fullfile(ref_dir, 'S.ref'), S_ref);
write_matrix_ref(fullfile(ref_dir, 'SAJ.ref'), SAJ_ref);
write_matrix_ref(fullfile(ref_dir, 'A00.ref'), A00_ref);

% Optional multilevel references: SAJ/A00 blocks per hierarchy level.
level_files = dir(fullfile(ref_dir, 'eulerian_dof_map.level*.ref'));
if ~isempty(level_files)
    level_nums = zeros(numel(level_files), 1);
    N_levels = zeros(numel(level_files), 1);
    maps = cell(numel(level_files), 1);
    for k = 1:numel(level_files)
        tok = regexp(level_files(k).name, 'eulerian_dof_map\.level([0-9]+)\.ref', 'tokens');
        if isempty(tok)
            error('Unexpected level map filename: %s', level_files(k).name);
        end
        ln = str2double(tok{1}{1});
        [ib2mat, ~, Nlev] = read_eulerian_dof_map(fullfile(ref_dir, level_files(k).name), -1);
        level_nums(k) = ln;
        N_levels(k) = Nlev;
        maps{k} = ib2mat;
    end
    N_fine = max(N_levels);
    dx_fine = Lx / N_fine;
    J_fine_mat = build_interp_matrix(X_nodes, N_fine, dx_fine, dx_fine);
    SAJ_u_by_N = containers.Map('KeyType', 'double', 'ValueType', 'any');
    SAJ_u_fine = J_fine_mat' * A * J_fine_mat;
    SAJ_u_by_N(N_fine) = SAJ_u_fine;
    N_curr = N_fine;
    SAJ_curr = SAJ_u_fine;
    while N_curr > min(N_levels)
        N_coarse = N_curr / 2;
        P_rt0 = build_rt0_prolongation_matrix(N_coarse);
        R_rt0 = build_rt0_restriction_matrix(N_curr);
        SAJ_curr = R_rt0 * SAJ_curr * P_rt0;
        SAJ_u_by_N(N_coarse) = SAJ_curr;
        N_curr = N_coarse;
    end

    for k = 1:numel(level_files)
        ln = level_nums(k);
        Nlev = N_levels(k);
        ib2mat = maps{k};
        if ~isKey(SAJ_u_by_N, Nlev)
            error('Missing transferred SAJ_u reference for N=%d', Nlev);
        end
        SAJ_u_mat = SAJ_u_by_N(Nlev);
        n_u_ln = Nlev * Nlev;
        ib2mat_u = ib2mat(1:(2 * n_u_ln));

        L_stokes = sparse(build_saddle_point_matrix_level_ib4_all(X_nodes, N_fine, dx_fine, ds, 0.0, dt, rho, mu, round(log2(N_fine / Nlev)) + 1));
        L_stokes_u = L_stokes(1:(2 * n_u_ln), 1:(2 * n_u_ln));
        A00_u_mat = L_stokes_u + SAJ_u_mat;
        A00_ref_ln = A00_u_mat(ib2mat_u, ib2mat_u);
        SAJ_u_ref_ln = SAJ_u_mat(ib2mat_u, ib2mat_u);

        write_matrix_ref(fullfile(ref_dir, sprintf('A00.level%d.ref', ln)), A00_ref_ln);
        write_matrix_ref(fullfile(ref_dir, sprintf('SAJ.level%d.ref', ln)), SAJ_u_ref_ln);
    end
end
end

function A = build_lagrangian_A(X_nodes, kappa, rest_len)
n_ib = size(X_nodes, 1);
A = sparse(2 * n_ib, 2 * n_ib);

% Match IBRedundantInitializer edge convention (master index < slave index):
% (1,2), (2,3), ..., (n-1,n), (1,n)
edges = [(1:(n_ib - 1))', (2:n_ib)'; 1, n_ib];

for e = 1:size(edges, 1)
    m = edges(e, 1);
    s = edges(e, 2);
    D = (X_nodes(s, :) - X_nodes(m, :))';
    R = norm(D);
    T = kappa * (R - rest_len);
    dT_dR = kappa;
    I2 = eye(2);
    dF = (T / R) * I2 + (dT_dR - T / R) * (D * D') / (R * R);

    mm = (2 * m - 1):(2 * m);
    ss = (2 * s - 1):(2 * s);
    A(mm, ss) = A(mm, ss) + dF;
    A(ss, mm) = A(ss, mm) + dF;
    A(mm, mm) = A(mm, mm) - dF;
    A(ss, ss) = A(ss, ss) - dF;
end
end

function saddle_point_matrix = build_saddle_point_matrix_level_ib4_all(X, N, h, ds, K, dt, rho, mu, level)
N_coarse = N / (2^(level - 1));
saddle_point_matrix = zeros(3 * N_coarse^2, 3 * N_coarse^2);
ej = zeros(3 * N_coarse^2, 1);
for j = 1:(3 * N_coarse^2)
    ej(j) = 1;
    Unew = apply_saddle_matrix_level_ib4_all(ej, X, N, h, ds, K, dt, rho, mu, level);
    saddle_point_matrix(:, j) = Unew;
    ej(j) = 0;
end
end

function Unew = apply_saddle_matrix_level_ib4_all(U, X, N, h, ds, K, dt, rho, mu, level)
dx_level = h * 2^(level - 1);
dy_level = h * 2^(level - 1);
N_coarse = N / 2^(level - 1);
u = reshape(U(1:N_coarse * N_coarse), N_coarse, N_coarse);
v = reshape(U(N_coarse^2 + 1:2 * N_coarse * N_coarse), N_coarse, N_coarse);
p = reshape(U(2 * N_coarse * N_coarse + 1:end), N_coarse, N_coarse);

Lapu = applyLap(u, dx_level, dy_level);
Lapv = applyLap(v, dx_level, dy_level);
[Gpx, Gpy] = applyGradP(p, dx_level, dy_level);
DivU = applyDivU(u, dx_level);
DivV = applyDivV(v, dy_level);

if level > 1
    num_prolongs = level - 1;
    [ufine, vfine] = apply_prolongation_rt0_mac(u, v);
    for j = 1:(num_prolongs - 1)
        [ufine, vfine] = apply_prolongation_rt0_mac(ufine, vfine);
    end
    [Uinterp, Vinterp] = interpIB4(ufine, vfine, X, h, h);
    Fnew = Elastic_Laplacian([Uinterp, Vinterp], K, ds);
    [ffx, ffy] = spreadIB4(Fnew, X, ufine, vfine, h, h, ds);
    for j = 1:num_prolongs
        [ffx, ffy] = apply_restriction_rt0_mac(ffx, ffy);
    end
    ffx = reshape(ffx(:), N_coarse, N_coarse);
    ffy = reshape(ffy(:), N_coarse, N_coarse);
else
    [Uinterp, Vinterp] = interpIB4(u, v, X, h, h);
    Fnew = Elastic_Laplacian([Uinterp, Vinterp], K, ds);
    [ffx, ffy] = spreadIB4(Fnew, X, u, v, h, h, ds);
end

unew = (rho / dt) .* u - mu .* Lapu - dt .* ffx + Gpx;
vnew = (rho / dt) .* v - mu .* Lapv - dt .* ffy + Gpy;
Unew = [unew(:); vnew(:); DivU(:) + DivV(:)];
end

function P = build_rt0_prolongation_matrix(Nc)
Nf = 2 * Nc;
ncf = Nc * Nc;
nf = Nf * Nf;
P = sparse(2 * nf, 2 * ncf);
for j = 1:(2 * ncf)
    uc = zeros(Nc, Nc);
    vc = zeros(Nc, Nc);
    if j <= ncf
        uc(j) = 1.0;
    else
        vc(j - ncf) = 1.0;
    end
    [uf, vf] = apply_prolongation_rt0_mac(uc, vc);
    P(:, j) = [uf(:); vf(:)];
end
end

function R = build_rt0_restriction_matrix(Nf)
Nc = Nf / 2;
nf = Nf * Nf;
ncf = Nc * Nc;
R = sparse(2 * ncf, 2 * nf);
for j = 1:(2 * nf)
    uf = zeros(Nf, Nf);
    vf = zeros(Nf, Nf);
    if j <= nf
        uf(j) = 1.0;
    else
        vf(j - nf) = 1.0;
    end
    [uc, vc] = apply_restriction_rt0_mac(uf, vf);
    R(:, j) = [uc(:); vc(:)];
end
end

function J = build_interp_matrix(X_nodes, N, dx, dy)
n_ib = size(X_nodes, 1);
n_u = N * N;
J = sparse(2 * n_ib, 2 * n_u);
for col = 1:(2 * n_u)
    u = zeros(N, N);
    v = zeros(N, N);
    if col <= n_u
        u(col) = 1.0;
    else
        v(col - n_u) = 1.0;
    end
    [U, V] = interpIB4(u, v, X_nodes, dx, dy);
    for k = 1:n_ib
        J(2 * k - 1, col) = U(k);
        J(2 * k, col) = V(k);
    end
end
end

function [ib_to_mat_idx, n_tot, N] = read_eulerian_dof_map(filename, N)
fid = fopen(filename, 'r');
if fid < 0
    error('Unable to open DOF map file: %s', filename);
end
cleanup = onCleanup(@() fclose(fid));
n_tot = fscanf(fid, '%d', 1);
if N < 0
    N = round(sqrt(n_tot / 3));
end
ib_to_mat_idx = zeros(n_tot, 1);
for k = 1:n_tot
    idx = fscanf(fid, '%d', 1);
    typ = fscanf(fid, '%c', 1); % consumes whitespace + char
    while typ == ' ' || typ == sprintf('\n') || typ == sprintf('\t')
        typ = fscanf(fid, '%c', 1);
    end
    axis = fscanf(fid, '%d', 1);
    i = fscanf(fid, '%d', 1);
    j = fscanf(fid, '%d', 1);
    if typ == 'u'
        if axis == 0
            mat_idx = (j + 1) + i * N;
        elseif axis == 1
            mat_idx = N * N + (j + 1) + i * N;
        else
            error('Invalid velocity axis in DOF map: %d', axis);
        end
    elseif typ == 'p'
        mat_idx = 2 * N * N + (j + 1) + i * N;
    else
        error('Invalid DOF type in map: %s', typ);
    end
    ib_to_mat_idx(idx + 1) = mat_idx;
end
end

function write_vector_ref(filename, v)
fid = fopen(filename, 'w');
if fid < 0
    error('Unable to open output file: %s', filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%d\n', numel(v));
for k = 1:numel(v)
    fprintf(fid, '%d %.17g\n', k - 1, v(k));
end
end

function write_matrix_ref(filename, A)
A(abs(A) <= 1.0e-13) = 0.0;
[i, j, s] = find(A);
[~, perm] = sortrows([i, j], [1, 2]);
i = i(perm); j = j(perm); s = s(perm);

fid = fopen(filename, 'w');
if fid < 0
    error('Unable to open output file: %s', filename);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%d %d %d\n', size(A, 1), size(A, 2), numel(s));
for k = 1:numel(s)
    fprintf(fid, '%d %d %.17g\n', i(k) - 1, j(k) - 1, s(k));
end
end
