// ---------------------------------------------------------------------
//
// Copyright (c) 2020 - 2023 by the IBAMR developers
// All rights reserved.
//
// This file is part of IBAMR.
//
// IBAMR is free software and is distributed under the 3-clause BSD
// license. The full text of the license can be found in the file
// COPYRIGHT at the top level directory of IBAMR.
//
// ---------------------------------------------------------------------

/////////////////////////////// INCLUDE GUARD ////////////////////////////////

#ifndef included_IBTK_MergingLoadBalancer
#define included_IBTK_MergingLoadBalancer

/////////////////////////////// INCLUDES /////////////////////////////////////

#include <ibtk/config.h>

#include "ibtk/IBTK_MPI.h"
#include "ibtk/samrai_compatibility_names.h"
#include <ibtk/box_utilities.h>

#include "SAMRAIBox.h"
#include "SAMRAIBoxList.h"
#include "SAMRAIIntVector.h"
#include "SAMRAILoadBalancer.h"
#include "SAMRAIPIO.h"
#include "SAMRAIPatchHierarchy.h"
#include "SAMRAIPointer.h"
#include "SAMRAIProcessorMapping.h"

#include <BoxArray.h>

#include <algorithm>
#include <set>
#include <utility>
#include <vector>

namespace SAMRAI
{
namespace hier
{
class ProcessorMapping;
template <int DIM>
class PatchHierarchy;
} // namespace hier
} // namespace SAMRAI

/////////////////////////////// CLASS DEFINITION /////////////////////////////

namespace IBTK
{
/*!
 * \brief Class MergingLoadBalancer merges the boxes generated by a load
 * balancer in a final step to decrease the total number of boxes. In essence,
 * it postprocesses the list of boxes generated by its parent class to try and
 * coalesce the set of boxes on each process.
 *
 * @note During regridding, the boxes generated by this class are subsequently
 * read by GriddingAlgorithm, which will enforce minimum and maximum size
 * constraints; i.e., to take full advantage of this class one must set up the
 * GriddingAlgorithm objects to have very large maximum box sizes.
 */
class MergingLoadBalancer : public SAMRAILoadBalancer
{
public:
    // use parent constructor
    using SAMRAILoadBalancer::LoadBalancer;

    virtual void loadBalanceBoxes(SAMRAI::hier::BoxArray<NDIM>& out_boxes,
                                  SAMRAIProcessorMapping& mapping,
                                  const SAMRAIBoxList& in_boxes,
                                  const SAMRAIPointer<SAMRAIPatchHierarchy> hierarchy,
                                  int level_number,
                                  const SAMRAI::hier::BoxArray<NDIM>& physical_domain,
                                  const SAMRAIIntVector& ratio_to_hierarchy_level_zero,
                                  const SAMRAIIntVector& min_size,
                                  const SAMRAIIntVector& max_size,
                                  const SAMRAIIntVector& cut_factor,
                                  const SAMRAIIntVector& bad_interval) const override;
};
} // namespace IBTK

//////////////////////////////////////////////////////////////////////////////

#endif // #ifndef included_IBTK_MergingLoadBalancer
